### ISSUE TITLE
Users can create challenges

### ISSUE THREAD

**Issue by n1c0z** [fac-13/Well-Bean#8]
Users can create challenges that follow the S.M.A.R.T pattern. (Specific, Measurable, Attainable, Relevant and Timely)

* [x] Make add challenge button on challenges page
* [x] Make add challenge form
* [x] Add endpoint for /add-challenge

Part of User Journey: User can submit new messages or challenges #27

**Comment by i2xzy** [comment]
Users can create challenges that follow the S.M.A.R.T pattern. (Specific, Measurable, Attainable, Relevant and Timely)
